# Generated by Django 4.1.2 on 2022-10-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoya_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excludedchannel',
            old_name='ch_id',
            new_name='discord_id',
        ),
    ]
