# Generated by Django 4.1.2 on 2022-10-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoya_site', '0002_rename_ch_id_excludedchannel_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='lvl',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='EXP',
        ),
    ]
