# Generated by Django 4.1.2 on 2022-10-28 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoya_site', '0003_discorduser_exp_discorduser_lvl_delete_exp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
